### ISSUE TITLE
Apphud compatibility with Google Play Billing 8.0

### ISSUE THREAD

**Issue by darkryh** [apphud/ApphudSDK-Android#117]
There is a crash that happens on Apphud when I upgrade my google play billing library from 7.1.1 to 8.0

```
  java.lang.NoSuchMethodError: No virtual method enablePendingPurchases()Lcom/android/billingclient/api/BillingClient$Builder; in class Lcom/android/billingclient/api/BillingClient$Builder; or its super classes (declaration of 'com.android.billingclient.api.BillingClient$Builder' appears in /data/app/~~0_y4v5sGPXEb5L-OeX_fhg==/com.hapday.healthy.solutions.hapday-L5RfYXfUFq6SGz_LTJAohQ==/base.apk!classes19.dex)
                                                                                                    	at com.apphud.sdk.internal.BillingWrapper.<init>(BillingWrapper.kt:29)
                                                                                             	at com.apphud.sdk.ApphudInternal.initialize$sdk_release(ApphudInternal.kt:237)
                                                                                                    	at com.apphud.sdk.Apphud.start(Apphud.kt:80)
                                                                                                    	at com.apphud.sdk.Apphud.start(Apphud.kt:30)
```

the method is removed from this version
So it generates that crash

**Comment by tlozovyi** [comment]
Also waiting for the Google Play Billing 8.0.

**Comment by DimaDDM** [comment]
When will Google Billing 8.0 support be ready?
